language: r

sudo: required

before_install:
  - sudo apt-get update
  # install library dependencies
  - sudo apt-get install libzbar0 make perl
  # Install exiftool
  #- wget https://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-11.76.tar.gz
  - wget https://exiftool.org/Image-ExifTool-11.94.tar.gz
  - tar -xzf Image-ExifTool-11.94.tar.gz 
  - pushd Image-ExifTool-11.94/
  - perl Makefile.PL 
  - make test
  - sudo make install
  - popd

  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin
  - sudo aptitude install -y libgdal1-dev
  - sudo aptitude install -y libproj-dev
